#!/usr/bin/env bash
# Install nginx on your web-01

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart
sudo service nginx reload
