#!/usr/bin/env bash
# install & configure nginx server

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

STR1="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$STR1/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
STR2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$STR2/" /etc/nginx/sites-enabled/default
#read -r -d '' STR2 << }
#listen 80 default_server;
#	error_page 404 /404.html
#	location /404.html {
#		root /var/www/html;
#		internal;
#	}

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo nginx restart
